import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useSession, signIn, signOut } from 'next-auth/react'

import styles from '#components/styles/Home.module.css'
import { repos, users } from '#components/graphql/assets'
import RepoCard from '#components/UI/RepoCard'
import UserCard from '#components/UI/UserCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { data: session } = useSession()
  // console.log(session);

  if (!session) {
    return (
      <main className={`${styles.main} ${inter.className}`}>
        Not signed in <br />
        <button onClick={() => signIn()}>Sign in</button>
      </main>
    )
  }

  return (
    <>
      <Head>
        <title>User/Repo search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className={styles.container}>
          <div className={styles.searchBar}>
            <input defaultValue={session.user?.name || ''} className={styles.input} type="text" />
            <button>
              search
            </button>
          </div>

          {/* <div className={styles.grid}>
            {repos.map(({node})=>{
              return(
                // @ts-ignore
                <RepoCard key={node.id} repo={node}/>
              )
            })}
          </div> */}
          <div className={styles.grid}>
            {users.map(({node})=>{
              return(
                // @ts-ignore
                <UserCard key={node.id} user={node}/>
              )
            })}
          </div>
        </div>
      </main>
    </>
  )
}
