import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
// import { useSession, signIn, signOut } from 'next-auth/react'
import SearchBar from '#components/components/Search'
import UsersList from '#components/components/UsersList'
import RepoList from '#components/components/RepoList'

import styles from '#components/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>User/Repo search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className={styles.container}>

          <SearchBar />

          <section className={styles.section}>
            <h2>Users</h2>
            <div className={styles.grid}>
              <UsersList />
            </div>
          </section>

          <section className={styles.section}>
            <h2>Repositories</h2>
            <div className={styles.grid}>
              <RepoList />
            </div>
          </section>

        </div>
      </main>
    </>
  )
}
